# Generated by Django 4.2 on 2023-07-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mailinglogs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsetting',
            name='log_time',
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='head_message',
            field=models.OneToOneField(default="<built-in function id>+'сообщение'", max_length=150, on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='head_message',
            field=models.CharField(default="<built-in function id>+'сообщение'", max_length=150, unique=True, verbose_name='Тема сообщения'),
        ),
    ]
