# Generated by Django 4.2 on 2023-07-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_mailingsetting_log_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='head_message',
            field=models.OneToOneField(default='сообщение', max_length=150, on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='head_message',
            field=models.OneToOneField(default='сообщение', max_length=150, on_delete=django.db.models.deletion.CASCADE, to='main.message', verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='head_message',
            field=models.CharField(default='сообщение', max_length=150, unique=True, verbose_name='Тема сообщения'),
        ),
    ]
